owner: loyds44 # Votre nom d'utilisateur GitHub
repo: uptime # Le nom de votre dépôt

sites:
  - name: Linksta
    url: https://linksta.cc/@loyds44

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status
  introTitle: "**Upptime** status page"
  introMessage: This page shows the uptime status of our monitored sites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
