owner: loyds44 # Votre nom d'utilisateur GitHub
repo: uptime   # Le nom de votre dépôt

sites:
  - name: Linksta
    url: https://linksta.cc/@loyds44
  - name: Google
    url: https://www.google.com/
  - name: Discord
    url: https://discord.com/

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status Loyds44
  introTitle: "**Upptime** status page"
  introMessage: This page shows the uptime status of our monitored sites.
  navbar:
    - title: Status
      href: /uptime/
    - title: GitHub
      href: https://github.com/loyds44/uptime

# Planification des workflows (en syntaxe cron)
workflowSchedule:
  uptime: "*/5 * * * *"         # Vérification de l'uptime toutes les 5 minutes
  responseTime: "*/5 * * * *"     # Enregistrement du temps de réponse toutes les 5 minutes
  graphs: "*/10 * * * *"          # Génération des graphiques toutes les 10 minutes
  staticSite: "*/15 * * * *"      # Mise à jour du site toutes les 15 minutes
  summary: "0 0 * * *"            # Mise à jour du résumé (par défaut, une fois par jour)
  updateTemplate: "0 0 * * *"     # Mise à jour du template (par défaut, une fois par jour)
  updates: "0 3 * * *"            # Autres mises à jour (par défaut)
