owner: loyds44
repo: uptime

sites:
  - name: Linksta
    url: https://linksta.cc/@loyds44
  - name: Google
    url: https://www.google.com/
  - name: Discord
    url: https://discord.com/

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status Loyds44
  introTitle: "**Upptime** status page"
  introMessage: This page shows the uptime status of our monitored sites.
  navbar:
    - title: Status
      href: /uptime/
    - title: GitHub
      href: https://github.com/loyds44/uptime

# Planification optimisée des workflows (cron)
workflowSchedule:
  uptime: "*/10 * * * *"         # Vérification de l'uptime toutes les 10 min 
  responseTime: "*/15 * * * *"   # Temps de réponse toutes les 15 min 
  graphs: "0,30 * * * *"         # Graphiques deux fois par heure 
  staticSite: "0 * * * *"        # Update site toutes les heures 
  summary: "0 0,12 * * *"        # Résumé deux fois/jour 
  updateTemplate: "0 2 * * *"    # Template maintenu à une fois/jour (ou moins)
  updates: "0 3 * * *"           # Autres maj inchangées
