owner: loyds44 # Votre nom d'utilisateur GitHub
repo: uptime   # Le nom de votre dépôt

sites:
  - name: Linksta
    url: https://linksta.cc/@loyds44
  - name: Google
    url: https://www.google.com/
  - name: Discord
    url: https://discord.com/

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status Loyds44
  introTitle: "**Upptime** status page"
  introMessage: This page shows the uptime status of our monitored sites.
  navbar:
    - title: Status
      href: /uptime/       
    - title: GitHub
      href: https://github.com/loyds44/uptime
